TOOLS = [
    {
        "name": "Kubernetes",
        "category": "Container Orchestration",
        "icon": "☸️",
        "source": "github_releases",
        "repo": "kubernetes/kubernetes",
        "homepage": "https://kubernetes.io/releases/",
    },
    {
        "name": "OpenShift OKD",
        "category": "Container Orchestration",
        "icon": "🔴",
        "source": "github_releases",
        "repo": "openshift/okd",
        "homepage": "https://okd.io/",
    },
    {
        "name": "Docker Engine",
        "category": "Containerization",
        "icon": "🐳",
        "source": "github_releases",
        "repo": "moby/moby",
        "tag_transform": "docker_engine",
        "homepage": "https://docs.docker.com/engine/release-notes/",
    },
    {
        "name": "Docker Compose",
        "category": "Containerization",
        "icon": "🐋",
        "source": "github_releases",
        "repo": "docker/compose",
        "homepage": "https://docs.docker.com/compose/release-notes/",
    },
    {
        "name": "Helm",
        "category": "Package Manager",
        "icon": "⛵",
        "source": "github_releases",
        "repo": "helm/helm",
        "homepage": "https://helm.sh/",
    },
    {
        "name": "Apache Kafka",
        "category": "Message Streaming",
        "icon": "📨",
        "source": "github_tags",
        "repo": "apache/kafka",
        "tag_transform": "kafka",
        "homepage": "https://kafka.apache.org/downloads",
    },
    {
        "name": "RabbitMQ",
        "category": "Message Broker",
        "icon": "🐰",
        "source": "github_releases",
        "repo": "rabbitmq/rabbitmq-server",
        "homepage": "https://www.rabbitmq.com/changelog.html",
    },
    {
        "name": "Apache NiFi",
        "category": "Data Integration",
        "icon": "🌊",
        "source": "github_tags",
        "repo": "apache/nifi",
        "tag_transform": "nifi",
        "homepage": "https://nifi.apache.org/download/",
    },
    {
        "name": "Redis",
        "category": "Cache / Database",
        "icon": "🔴",
        "source": "github_releases",
        "repo": "redis/redis",
        "homepage": "https://redis.io/downloads/",
    },
    {
        "name": "MySQL Community",
        "category": "Database",
        "icon": "🐬",
        "source": "dockerhub",
        "repo": "library/mysql",
        "homepage": "https://dev.mysql.com/downloads/mysql/",
    },
    {
        "name": "PostgreSQL",
        "category": "Database",
        "icon": "🐘",
        "source": "github_tags",
        "repo": "postgres/postgres",
        "tag_transform": "postgres",
        "homepage": "https://www.postgresql.org/ftp/latest/",
    },
    {
        "name": "Elasticsearch",
        "category": "Search Engine",
        "icon": "🔍",
        "source": "github_releases",
        "repo": "elastic/elasticsearch",
        "homepage": "https://www.elastic.co/downloads/elasticsearch",
    },
    {
        "name": "JupyterLab",
        "category": "Data Science IDE",
        "icon": "📓",
        "source": "github_releases",
        "repo": "jupyterlab/jupyterlab",
        "homepage": "https://jupyterlab.readthedocs.io/en/stable/",
    },
    {
        "name": "Terraform",
        "category": "IaC",
        "icon": "🏗️",
        "source": "github_releases",
        "repo": "hashicorp/terraform",
        "homepage": "https://developer.hashicorp.com/terraform/downloads",
    },
    {
        "name": "Ansible",
        "category": "Config Management",
        "icon": "🤖",
        "source": "github_releases",
        "repo": "ansible/ansible",
        "homepage": "https://github.com/ansible/ansible/releases",
    },
    {
        "name": "ArgoCD",
        "category": "GitOps",
        "icon": "🐙",
        "source": "github_releases",
        "repo": "argoproj/argo-cd",
        "homepage": "https://github.com/argoproj/argo-cd/releases",
    },
    {
        "name": "Prometheus",
        "category": "Monitoring",
        "icon": "🔥",
        "source": "github_releases",
        "repo": "prometheus/prometheus",
        "homepage": "https://prometheus.io/download/",
    },
    {
        "name": "Grafana",
        "category": "Visualization",
        "icon": "📊",
        "source": "github_releases",
        "repo": "grafana/grafana",
        "homepage": "https://grafana.com/grafana/download",
    },
    {
        "name": "Jenkins",
        "category": "CI/CD",
        "icon": "🤵",
        "source": "github_releases",
        "repo": "jenkinsci/jenkins",
        "homepage": "https://www.jenkins.io/changelog/",
    },
    {
        "name": "Nginx",
        "category": "Web Server",
        "icon": "🌐",
        "source": "github_tags",
        "repo": "nginx/nginx",
        "tag_transform": "nginx",
        "homepage": "https://nginx.org/en/download.html",
    },
    {
        "name": "VMware vSphere",
        "category": "Virtualization",
        "icon": "💻",
        "source": "static",
        "homepage": "https://docs.vmware.com/en/VMware-vSphere/index.html",
        "versions": [
            {"version": "8.0 Update 3", "release_date": "2024-07-02"},
            {"version": "8.0 Update 2", "release_date": "2023-12-14"},
        ],
    },
]
